CoreAndFood/Controllers/FoodController.cs
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;
using CoreAndFood.Data.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using X.PagedList;

namespace CoreAndFood.Controllers
{
    public class FoodController : Controller
    {
        FoodRepository foodRepository = new FoodRepository(); // Global Object
        Context context = new Context();

        public IActionResult Index(int page = 1)
        {
            return View(foodRepository.TList("Category").ToPagedList(page, 3));
        }


        [HttpGet]
        public IActionResult AddFood()
        {
            List<SelectListItem> selectLists = (from item in context.Categories.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = item.CategoryName,
                                                    Value = item.CategoryID.ToString()

                                                }).ToList();
            ViewBag.value = selectLists;
            return View();
        }

        [HttpPost]
        public IActionResult AddFood(Food food)
        {
            foodRepository.TAdd(food);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteFood(int id) {

            var food = context.Foods.Find(id);
            foodRepository.TDelete(food); // Bir diğer yöntemde burada Food'u newleyip, FoodID ye; gelen id paremetresini atarak silebilirim
            return RedirectToAction("Index");
        }

        public IActionResult FoodGet(int id)
        {
            var x = foodRepository.TGet(id);

            List<SelectListItem> selectLists = (from items in context.Categories.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = items.CategoryName,
                                                    Value = items.CategoryID.ToString()

                                                }).ToList();
            ViewBag.value = selectLists;

            Food food = new Food()
            {
                FoodID = x.FoodID,
                CategoryID = x.CategoryID,
                Name = x.Name,
                Price = x.Price,
                Stock = x.Stock,
                Description = x.Description,
                ImageURL = x.ImageURL
            };

            return View(food);
        }

        [HttpPost]
        public IActionResult FoodUpdate(Food food)
        {
            var x = foodRepository.TGet(food.FoodID);
            x.Name = food.Name;
            x.Stock = food.Stock;
            x.Description = food.Description;
            x.ImageURL = food.ImageURL;
            x.Price = food.Price;
            x.CategoryID = food.CategoryID;

            foodRepository.TUpdate(x);

            return RedirectToAction("Index");
        }

    }
}

CoreAndFood/Views/Food/AddFood.cshtml
@model CoreAndFood.Data.Models.Food


@{
    ViewData["Title"] = "AddFood";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add Food Page</h1>
<br />

@using(Html.BeginForm("AddFood", "Food", FormMethod.Post))
{

    <h4>Food Name</h4>
    @Html.TextBoxFor(x => x.Name , new {@class="form form-control"})

    <h4>Description</h4>
    @Html.TextBoxFor(x => x.Description , new {@class="form form-control"})

    <h4>Price ₺</h4>
    @Html.TextBoxFor(x => x.Price , new {@class="form form-control"})

    <h4>Image URL</h4>
    @Html.TextBoxFor(x => x.ImageURL , new {@class="form form-control"})

    <h4>Stock</h4>
    @Html.TextBoxFor(x => x.Stock , new {@class="form form-control"})

    <h4>Category Name</h4>
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.value, new {@class = "form form-control"})

    <br />

    <button class="btn btn-info">Save</button>
}

CoreAndFood/Views/Food/FoodGet.cshtml
@model CoreAndFood.Data.Models.Food
@{
    ViewData["Title"] = "FoodGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update Food Page</h1>
<br />

@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
    <h4>Food İd</h4>
    @Html.TextBoxFor(x => x.FoodID , new {@class="form form-control"})

    <h4>Food Name</h4>
    @Html.TextBoxFor(x => x.Name , new {@class="form form-control"})

    <h4>Category Name</h4>
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.value, new {@class = "form form-control"})

    <h4>Price ₺</h4>
    @Html.TextBoxFor(x => x.Price , new {@class="form form-control"})

    <h4>Stock</h4>
    @Html.TextBoxFor(x => x.Stock , new {@class="form form-control"})

    <h4>Image URL</h4>
    @Html.TextBoxFor(x => x.ImageURL , new {@class="form form-control"})

    <h4>Description</h4>
    @Html.TextBoxFor(x => x.Description , new {@class="form form-control"})

    <br />

    <button class="btn btn-info">Save</button>
}

CoreAndFood/Views/Food/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core

@model IPagedList<CoreAndFood.Data.Models.Food>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Food List</h1>
<br />

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Food Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Category Name</th>
        <th>Delete</th>
        <th>Update</th>
        <th>Details</th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.FoodID</th>
            <td>@item.Name</td>
            <td>@item.Price</td>
            <td>@item.Stock</td>
            <td>@item.Category.CategoryName</td>
            <td><a href="#" class="btn btn-danger">Delete</a></td>
            <td><a href="/Food/FoodGet/@item.FoodID" class="btn btn-success">Update</a></td>
             <td><a href="#" class="btn btn-info">Details</a></td>
        </tr>
    }

</table>
@Html.PagedListPager((IPagedList)Model , page => Url.Action("Index" , new {page}))


<a href="/Food/AddFood" class="btn btn-primary">New Food</a>
<br />