CoreAndFood/Controllers/ChartController.cs
using CoreAndFood.Data;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using CoreAndFood.Data.Models;
using System.Linq;

namespace CoreAndFood.Controllers
{
    public class ChartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Index2()
        {
            return View();
        }

        public IActionResult VisualizeProductResult()
        {
            return Json(ProductList());
        }

        public List<Class1> ProductList()
        {
            List<Class1> productList = new List<Class1>();
            productList.Add(new Class1()
            {
                productName = "Computer",
                stock = 120
            });

            productList.Add(new Class1()
            {
                productName = "Keyboard",
                stock = 45
            });

            productList.Add(new Class1()
            {
                productName = "Mouse",
                stock = 220
            });

            return productList;
        }

        public IActionResult Index3()
        {
            return View();
        }
        public List<Class2> FoodList()
        {
            List<Class2> class2 = new List<Class2>();
            using(var context = new Context())
            {
                class2 = context.Foods.Select(x => new Class2() { foodName = x.Name, stock = x.Stock }).ToList();
                return class2;
            }
        }

        public IActionResult VisualizeProductResult2()
        {
            return Json(FoodList());
        }

        public IActionResult Statistics()
        {
            Context context = new Context();

            // Toplam Yemek Sayısı
            var value1 = context.Foods.Count();
            ViewBag.val1 = value1;


            // Toplam Kategori Sayısı
            var value2 = context.Categories.Count();
            ViewBag.val2 = value2;


            // Meyve Kategorisinde Kaç tane ürün var
            var foodİd = context.Categories.Where(x => x.CategoryName == "Fruit").
                Select(y => y.CategoryID).
                FirstOrDefault();

            var value3 = context.Foods.Where(x => x.CategoryID == foodİd).Count();
            ViewBag.val3 = value3;


            //Sebze Kategorisinde kaç tane ürün var
            var value4 = context.Foods.Where(x => x.CategoryID == context.Categories.Where(z => z.CategoryName == "Vegetables").
                Select(y => y.CategoryID).
                FirstOrDefault()).Count();
            ViewBag.val4 = value4;


            //Yemek Tablosunda Toplamda Kaç Ürün var (Her Yemeğin Stok Adedini topla)
            var value5 = context.Foods.Sum(x => x.Stock);
            ViewBag.val5 = value5;


            // Baklagillerden Kaç Ürün Var
            var value6 = context.Foods.Where(x => x.CategoryID == context.Categories.Where(y => y.CategoryName == "Legumes").Select(z => z.CategoryID)
            .FirstOrDefault()).Count();
            ViewBag.val6 = value6;


            // Food Tablosunda Stok Adedi En Fazla Olan Ürünü Getir.
            var value7 = context.Foods.OrderByDescending(x => x.Stock).Select(y => y.Name).FirstOrDefault();
            ViewBag.val7 = value7;


            // Food Tablosunda stok adedi en az olan Ürünü getir.
            var value8 = context.Foods.OrderBy(x => x.Stock).Select(y => y.Name).FirstOrDefault();
            ViewBag.val8 = value8;


            // Foodların ortalama satış fiyatı
            var value9 = context.Foods.Average(x => x.Price).ToString("0.00"); // Formatlama işlemi / değer 0.00 şeklinde gözüksün
            ViewBag.val9 = value9;


            // Bir Kategorinin İçinde Bulunan Toplam Ürün/meyve Sayısı : Fruit
            var value10 = context.Categories.Where(x => x.CategoryName == "Fruit").Select(y => y.CategoryID).FirstOrDefault();
            var deger10Plus = context.Foods.Where(y => y.CategoryID == value10).Sum(x => x.Stock);
            ViewBag.val10 = deger10Plus;


            // Bir Kategorinin İçinde Bulunan Toplam Ürün/meyve Sayısı : Vegetables
            var value11 = context.Categories.Where(x => x.CategoryName == "Vegetables").Select(y => y.CategoryID).FirstOrDefault();
            var deger11Plus = context.Foods.Where(y => y.CategoryID == value11).Sum(x => x.Stock);
            ViewBag.val11 = deger11Plus;

            var value12 = context.Foods.OrderByDescending(x => x.Price).Select(y => y.Name).FirstOrDefault();
            ViewBag.val12 = value12;

            return View();


        }

        
        
    }
}

CoreAndFood/Views/Chart/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Index4";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.productName, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

CoreAndFood/Views/Chart/Index2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Index4";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.productName, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.ColumnChart(document
                .getElementById('ColumnChart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="ColumnChart_div"></div>
</body>
</html>

CoreAndFood/Views/Chart/Index3.cshtml
@{
    ViewData["Title"] = "Index4";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeProductResult2", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.foodName, obj.stock]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Food - Stock Dynamik Chart",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

CoreAndFood/Views/Chart/Statistics.cshtml
@{
    ViewData["Title"] = "Statistics";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content"> 
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">

                    <h3>@ViewBag.val1</h3>
                    <p>Total Food</p>

                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.val2</h3>
                    <p>Total Category</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.val3</h3>
                    <p>Fruit Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.val4</h3>
                    <p>Vegetable Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.val5</h3>
                    <p>Sum Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">
                    <h3>@ViewBag.val6</h3>
                    <p>Legumes Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.val7</h3>
                    <p>Max Stock Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.val8</h3>
                    <p>Min Stock Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

     <div class="total-content" >
        <div class="list_of_members">
            <div class="sales" style="background-color:#01a3a4">
                <div class="icon-text">
                    <h3>@ViewBag.val9 ₺</h3>
                    <p>Food Price Avg</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#ffb142">

                <div class="icon-text">
                    <h3> @ViewBag.val11</h3>
                    <p> Sum Vegetables</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#40407a">

                <div class="icon-text">
                    <h3>@ViewBag.val10</h3>
                    <p>Sum Fruit</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#4b4b4b">

                <div class="icon-text">
                    <h3>@ViewBag.val12</h3>
                    <p>Max Price Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>